from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.db.database import get_db
from app.models.weather import WeatherData
import pandas as pd
import os

router = APIRouter()

# Simple mock for now
def get_current_user():
    pass

@router.get("/current/{location}")
def get_current_weather(location: str, db: Session = Depends(get_db)):
    """
    Get the most recent weather data for a location.
    """
    data = db.query(WeatherData).filter(WeatherData.location_name == location).order_by(WeatherData.recorded_at.desc()).first()
    if not data:
        # Fallback to dummy data
        file_path = f"../data/{location.replace(' ', '_').lower()}_historical.csv"
        if os.path.exists(file_path):
            df = pd.read_csv(file_path)
            latest = df.iloc[-1].to_dict()
            return latest
        raise HTTPException(status_code=404, detail="Weather data not found")
    return data

@router.get("/historical/{location}")
def get_historical_weather(location: str, days: int = 30, db: Session = Depends(get_db)):
    """
    Get historical weather data.
    """
    # For MVP, we serve from the CSV generated by the script
    file_path = f"../data/{location.replace(' ', '_').lower()}_historical.csv"
    if os.path.exists(file_path):
        df = pd.read_csv(file_path)
        recent = df.tail(days).to_dict(orient='records')
        return recent
    raise HTTPException(status_code=404, detail="Historical data not found")
